config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  #CRUD for Images
  resources :images, only: [:index, :create, :new, :destroy]

  #Static Pages
  get 'pages/faq'
  get 'pages/contact'

  #Root Path
    root 'images#index'
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true

  belongs_to :stylist
end

app/models/stylist.rb
class Stylist < User
  has_many :images
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to images_path, notice: "The style you have added #{@image.name}, has been uploaded"
    else
      render "new"
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path, notice: "You have deleted your style #{@image.name}."
  end

  private
  def image_params
    params.require(:image).permit(:name, :attachment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end

  def faq
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Image", new_image_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= link_to "Download Image", image.attachment_url %></td>
        <td><%= button_to "Delete",  image, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{image.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/new.html.erb</p>

<% if !@image.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @image, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thatstyle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

    <% if (!user_signed_in?) %>
      <main class="mdl-layout__content">
        <div class="page-content">
          <%= render 'partials/header' %>
          <%= render 'partials/landing' %>
        </div>
      </main>
    <% else %>

      <main class="mdl-layout__content">
        <div class="page-content">
          <%= render 'partials/header' %>
            <div class="mdl-grid">
              <%= yield %>
            </div>

        </div>
    </main>
    <% end %>
  </div>



</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

app/views/pages/faq.html.erb
<h1>FAQ</h1>
<p>Please show god dam it</p>

app/views/partials/_header.html.erb
<!-- Always shows a header, even in smaller screens. -->
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to "thatStyle", root_path%></span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">

        <% if current_user %>
          <button id="demo-menu-lower-left" class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
          </button>

          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="demo-menu-lower-left">
            <li class="mdl-menu__item"><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li class="mdl-menu__item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li class="mdl-menu__item"><%= link_to "Sign In", new_user_session_path %></li>
            <li class="mdl-menu__item"><%= link_to "Sign Up", new_user_registration_path %>li>
        <% end %>
            <li class="mdl-menu__item"><%= link_to "FAQ", pages_faq_path %></li>
            <li class="mdl-menu__item"><%= link_to "Contact Us", pages_contact_path %></li>
          </ul>

        <% if current_user %>
          <span> Hello <%= current_user.first_name || current_user.email %>! </span>
        <% else %>
        <a class="mdl-navigation__link" href=""><%= link_to "Sign In", new_user_session_path %></a>
        <a class="mdl-navigation__link" href=""><%= link_to "Sign Up", new_user_registration_path %></a>
        <% end %>
      </nav>
    </div>
  </header>

app/views/partials/_landing.html.erb
<div id="bg">
  <img src="https://stylewatch.files.wordpress.com/2016/04/giphy.gif" alt="">
</div>

<div class="mdl-cell mdl-cell--6-col">
  <div style="padding-top: 20%; padding-left: 20px;">
      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div style="padding: 50px 50px 50px 50px;">
          <h1>Welcome to thatStyle</h1>
          <h4>A place where potential seeker and stylist can link together on something that
          they love....a new look....a new STYLE!</h4>
        </div>
      </div>
    </div>
</div>